language: perl
dist: trusty
perl:
  - "5.30"
  - "5.22"
  - "5.10"
sudo: false
before_install:
  - cpanm --quiet --notest Perl::Critic
install:
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - cpanm --quiet --notest DBI IPC::Shareable Parallel::ForkManager Digest::HMAC_SHA1 String::Escape XML::LibXML Net::SFTP::Foreign IO::Pty Test::mysqld
  - dzil build --in build --notgz
script:
  - perlcritic --single-policy=RequireTidyCode bin
  - cd build && RELEASE_TESTING=1 AUTHOR_TESTING=1 NO_DB_TESTING=1 prove --timer --lib --recurse --jobs 2 --shuffle t/